#!/usr/bin/env bash
set -uo pipefail
PROJECT="$1"; STATE_DIR="$2"; RUN_ID="$3"; TASK="$4"
STATE_FILE="$STATE_DIR/runs/$RUN_ID/state.json"
SHIPPED=false
PROTECTED="main master"

is_protected() { for p in $PROTECTED; do [ "$1" = "$p" ] && return 0; done; return 1; }

cd "$PROJECT" || exit 1
echo "━━━ Ship ━━━"
echo "Run: $RUN_ID | Project: $(basename "$PROJECT")"
echo "Watching: $STATE_FILE"
echo ""

while true; do
  # Status display
  BRANCH=$(git branch --show-current 2>/dev/null || echo 'detached')
  printf "\r[%s] Branch: %s" "$(date '+%H:%M:%S')" "$BRANCH"

  # Check FUGUE state
  if [ -f "$STATE_FILE" ]; then
    PHASE=$(jq -r '.phase' "$STATE_FILE" 2>/dev/null)

    if [ "$PHASE" = "done" ] && ! $SHIPPED; then
      echo ""
      echo "━━━ FUGUE DONE — Auto-shipping ━━━"

      # FIX BUG 1: Re-read changes AFTER phase=done, with brief settle delay
      sleep 2
      CHANGES=$(git status --short 2>/dev/null | wc -l | tr -d ' ')

      if [ "$CHANGES" -eq 0 ]; then
        # Retry once after 5s (files may still be flushing)
        sleep 5
        CHANGES=$(git status --short 2>/dev/null | wc -l | tr -d ' ')
        if [ "$CHANGES" -eq 0 ]; then
          echo "No changes to ship (clean tree)"
          SHIPPED=true; continue
        fi
      fi

      # Protected branch check
      if is_protected "$BRANCH"; then
        echo "ABORT: on protected branch ($BRANCH)"
        echo "Create a feature branch first"
        SHIPPED=true; continue
      fi

      # FIX BUG 2: Stage both modified AND new files
      git diff --name-only 2>/dev/null | while IFS= read -r f; do
        [ -f "$f" ] && git add "$f"
      done
      git ls-files --others --exclude-standard 2>/dev/null | while IFS= read -r f; do
        [ -f "$f" ] && git add "$f"
      done

      # Commit
      COMMIT_MSG="${TASK:-Canon v4 auto-commit}

Run: $RUN_ID
Verified: FUGUE pipeline passed

Co-Authored-By: Canon v4 Shipper <noreply@cursorvers.com>"
      if git commit -m "$COMMIT_MSG" 2>&1; then
        echo "Committed on $BRANCH"
      else
        echo "COMMIT FAILED"; SHIPPED=true; continue
      fi

      # Push
      if git push -u origin "$BRANCH" 2>&1; then
        echo "Pushed to origin/$BRANCH"
      else
        echo "PUSH FAILED"; SHIPPED=true; continue
      fi

      # FIX BUG 4: PR title fallback for empty TASK
      PR_TITLE="${TASK:0:70}"
      PR_TITLE="${PR_TITLE:-Canon v4 auto-commit}"
      if command -v gh >/dev/null 2>&1; then
        EXISTING=$(gh pr list --head "$BRANCH" --state open --json number --jq '.[0].number' 2>/dev/null)
        if [ -z "$EXISTING" ]; then
          PR_URL=$(gh pr create --title "$PR_TITLE" --body "## Summary
Auto-generated by Canon v4 Ship pane.
Run: $RUN_ID

---
Generated by Canon v4" 2>&1) || true
          echo "$PR_URL" | grep -q 'https://' && echo "PR: $PR_URL" || echo "PR creation skipped"
        else
          echo "PR #$EXISTING exists"
        fi
      fi

      echo "━━━ SHIPPED ━━━"
      SHIPPED=true

    elif [ "$PHASE" = "blocked" ]; then
      echo ""
      echo "BLOCKED — needs human intervention"
    fi
  fi

  sleep 5
done
