name: FUGUE Task (Mobile / Natural Language)
description: Smartphone-first entrypoint. Adds label fugue-task automatically.
title: "task: "
labels:
  - fugue-task
body:
  - type: markdown
    attributes:
      value: |
        This template automatically applies label `fugue-task`.

        Mainframe behavior:
        - `Mainframe handoff = auto` sends this issue to Tutti (`tutti` label is applied by router).
        - Natural-language/default path is **review-first**.
        - Implementation execution needs both `implement` and `implement-confirmed`.
        - `Orchestrator provider` selects routing profile only. The implementation engine is `fugue-codex-implement` (Codex CLI).

        Tip: if you include a target repo in backticks like `cursorvers/cloudflare-workers-hub`, FUGUE will label and prefix the issue title so you can quickly see which project it belongs to.

  - type: dropdown
    id: mainframe_handoff
    attributes:
      label: Mainframe handoff
      description: Auto = route into Tutti pipeline. Manual = keep for human/manual handling.
      options:
        - auto
        - manual
      default: 0
    validations:
      required: true

  - type: dropdown
    id: execution_mode
    attributes:
      label: Execution mode
      description: Default is review. Choose implement only when you want autonomous code changes/PR flow.
      options:
        - review
        - implement
      default: 0
    validations:
      required: true

  - type: dropdown
    id: implementation_confirmation
    attributes:
      label: Implementation confirmation
      description: Required to actually execute implementation.
      options:
        - pending
        - confirmed
      default: 0
    validations:
      required: true

  - type: dropdown
    id: main_orchestrator_provider
    attributes:
      label: Main orchestrator provider
      description: Routing profile for Tutti voting lanes.
      options:
        - repository default
        - codex
        - claude
      default: 0
    validations:
      required: true

  - type: dropdown
    id: assist_orchestrator_provider
    attributes:
      label: Assist orchestrator provider
      description: Secondary routing profile.
      options:
        - repository default
        - claude
        - codex
        - none
      default: 0
    validations:
      required: true

  - type: dropdown
    id: multi_agent_mode
    attributes:
      label: Multi-agent mode
      description: Auto lets router decide by task complexity.
      options:
        - auto
        - standard
        - enhanced
        - max
      default: 0
    validations:
      required: true

  - type: input
    id: target_repo
    attributes:
      label: Target repo (optional)
      description: If the work is for another repo, put owner/repo here.
      placeholder: cursorvers/fugue-orchestrator
    validations:
      required: false

  - type: textarea
    id: goal
    attributes:
      label: Goal
      description: What outcome do you want? (write in natural language)
      placeholder: |
        完遂
        目的: ...
    validations:
      required: true

  - type: textarea
    id: must_not
    attributes:
      label: Must not
      description: Constraints / things the automation must not do.
      placeholder: |
        Must not: ...
        (例) レビューのみ / PR作成しない
    validations:
      required: false

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria (optional)
      description: Concrete checks to know it's done.
      placeholder: |
        - ...
    validations:
      required: false
