#!/usr/bin/env bash
set -euo pipefail

ROOT="/Users/masayuki/Dev/fugue-orchestrator/apps/happy-web"
STATE="$ROOT/src/kernel-state.js"
APP="$ROOT/src/app.js"
HTML="$ROOT/index.html"
INTAKE="$ROOT/src/adapters/happy-app-intake.js"
STATE_ADAPTER="$ROOT/src/adapters/happy-app-state.js"
RECOVERY="$ROOT/src/adapters/happy-app-recovery.js"
CROW="$ROOT/src/adapters/happy-app-crow.js"
CONFIG="$ROOT/src/config/happy-runtime-config.js"
ENDPOINT_CLIENT="$ROOT/src/adapters/happy-endpoint-client.js"

grep -q 'source: "happy-app"' "$INTAKE"
grep -q 'task_type' "$INTAKE"
grep -q 'requested_recovery_action' "$INTAKE"
grep -q 'created_at' "$STATE_ADAPTER"
grep -q 'is_primary' "$STATE_ADAPTER"
grep -q 'createCrowAdapter' "$STATE"
grep -q 'resolveHappyRuntimeConfig' "$STATE"
grep -q 'createEndpointClient' "$STATE"
grep -q 'createStateAdapter' "$STATE"
grep -q 'createRecoveryAdapter' "$STATE"
grep -q 'summarizeAcceptedPacket' "$CROW"
grep -q 'submitPrompt' "$STATE_ADAPTER"
grep -q 'setRecoverResult' "$STATE_ADAPTER"
grep -q 'syncRemoteState' "$STATE_ADAPTER"
grep -q 'remoteEnabled' "$CONFIG"
grep -q 'happy-state-endpoint' "$CONFIG"
grep -q 'fetchJson' "$ENDPOINT_CLIENT"
grep -q 'continuity-canary' "$RECOVERY"
grep -q 'recover-actions' "$HTML"
grep -q 'normalizeState' "$STATE_ADAPTER"
grep -q 'task-sheet' "$HTML"
grep -q 'buildIntakePacket' "$STATE"
grep -q 'openTaskSheet' "$APP"
grep -q 'wireRecoverActions' "$APP"
grep -q 'listActions()' "$APP"

echo "PASS [apps-happy-web-state-contract]"
