#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
STATE="$ROOT/src/kernel-state.js"
APP="$ROOT/src/app.js"
HTML="$ROOT/index.html"
INTAKE="$ROOT/src/adapters/happy-app-intake.js"
STATE_ADAPTER="$ROOT/src/adapters/happy-app-state.js"
RECOVERY="$ROOT/src/adapters/happy-app-recovery.js"
CROW="$ROOT/src/adapters/happy-app-crow.js"
CONFIG="$ROOT/src/config/happy-runtime-config.js"
ENDPOINT_CLIENT="$ROOT/src/adapters/happy-endpoint-client.js"
PROTOCOL="$ROOT/src/domain/happy-event-protocol.js"

grep -q 'source: "happy-app"' "$INTAKE"
grep -q 'task_type' "$INTAKE"
grep -q 'requested_recovery_action' "$INTAKE"
grep -q 'idempotency_key' "$INTAKE"
grep -q 'enqueuePacket' "$INTAKE"
grep -q 'enqueueRecoveryAction' "$INTAKE"
grep -q 'Local queue is full' "$INTAKE"
grep -q 'created_at' "$STATE_ADAPTER"
grep -q 'is_primary' "$STATE_ADAPTER"
grep -q 'eventLog' "$STATE_ADAPTER"
grep -q 'queue-enqueued' "$STATE_ADAPTER"
grep -q 'payload?.cursor' "$STATE_ADAPTER"
grep -q 'subscribe(listener)' "$STATE_ADAPTER"
grep -q 'syncTaskDetail' "$STATE_ADAPTER"
grep -q 'LIVE_TASK_STATUSES' "$PROTOCOL"
grep -q 'QUEUE_KINDS' "$PROTOCOL"
grep -q 'createCrowAdapter' "$STATE"
grep -q 'resolveHappyRuntimeConfig' "$STATE"
grep -q 'createEndpointClient' "$STATE"
grep -q 'createStateAdapter' "$STATE"
grep -q 'createRecoveryAdapter' "$STATE"
grep -q 'summarizeAcceptedPacket' "$CROW"
grep -q 'submitPrompt' "$STATE_ADAPTER"
grep -q 'requestRecoveryAction' "$STATE_ADAPTER"
grep -q 'syncRemoteState' "$STATE_ADAPTER"
grep -q 'remoteEnabled' "$CONFIG"
grep -q 'happy-state-endpoint' "$CONFIG"
grep -q 'happy-events-endpoint' "$CONFIG"
grep -q 'happy-task-detail-endpoint' "$CONFIG"
grep -q 'fetchJson' "$ENDPOINT_CLIENT"
grep -q 'continuity-canary' "$RECOVERY"
grep -q 'recover-actions' "$HTML"
grep -q 'normalizeState' "$STATE_ADAPTER"
grep -q 'task-sheet' "$HTML"
grep -q 'event-stream' "$HTML"
grep -q 'buildIntakePacket' "$STATE"
grep -q 'openTaskSheet' "$APP"
grep -q 'stateAdapter.subscribe' "$APP"
grep -q 'stateAdapter.syncTaskDetail' "$APP"
grep -q 'wireRecoverActions' "$APP"
grep -q 'listActions()' "$APP"

echo "PASS [apps-happy-web-state-contract]"
