#!/usr/bin/env bash
set -euo pipefail

MODE="smoke"
RUN_DIR=""
WORK_DIR="${NOTE_MANUSCRIPT_DIR:-/Users/masayuki/note-manuscript}"
TEMPLATE_REL="${NOTE_MANUSCRIPT_TEMPLATE_REL:-templates/article-template.md}"
DRAFTS_REL="${NOTE_MANUSCRIPT_DRAFTS_REL:-drafts}"

usage() {
  cat <<'EOF'
Usage: note-semi-auto.sh [options]

Options:
  --mode <smoke|execute>   Run mode (default: smoke)
  --run-dir <path>         FUGUE run directory (optional)
  -h, --help               Show help
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --mode)
      MODE="${2:-}"
      shift 2
      ;;
    --run-dir)
      RUN_DIR="${2:-}"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown option: $1" >&2
      exit 2
      ;;
  esac
done

if [[ "${MODE}" != "smoke" && "${MODE}" != "execute" ]]; then
  echo "Error: --mode must be smoke|execute" >&2
  exit 2
fi

template_path="${WORK_DIR}/${TEMPLATE_REL}"
drafts_dir="${WORK_DIR}/${DRAFTS_REL}"

[[ -d "${WORK_DIR}" ]] || { echo "note-semi-auto: missing work dir: ${WORK_DIR}" >&2; exit 1; }
[[ -f "${template_path}" ]] || { echo "note-semi-auto: missing template: ${template_path}" >&2; exit 1; }
mkdir -p "${drafts_dir}"

echo "note-semi-auto: mode=${MODE} work_dir=${WORK_DIR}"
if [[ "${MODE}" == "execute" ]]; then
  issue_number="${FUGUE_ISSUE_NUMBER:-unknown}"
  ts="$(date +%Y%m%d-%H%M%S)"
  out_file="${drafts_dir}/fugue-issue-${issue_number}-${ts}.md"
  cp "${template_path}" "${out_file}"
  {
    echo ""
    echo "---"
    echo "Generated by FUGUE linked system"
    echo "issue: #${issue_number}"
    echo "title: ${FUGUE_ISSUE_TITLE:-}"
    echo "generated_at_utc: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  } >> "${out_file}"
  echo "note-semi-auto: draft scaffold created: ${out_file}"
fi

if [[ -n "${RUN_DIR}" ]]; then
  mkdir -p "${RUN_DIR}"
  {
    echo "system=note-semi-auto"
    echo "mode=${MODE}"
    echo "work_dir=${WORK_DIR}"
    echo "template=${template_path}"
  } > "${RUN_DIR}/note-semi-auto.meta"
fi

